### ISSUE TITLE
ALL PLATFORMS: header image vimeo button

### ISSUE THREAD

**Issue by japhiaolson** [japhiaolson/themoneyfish#1]
This button should be separate from the actual image and should be clickable to bring up a fullscreen vimeo video which you can then close.
Should work on all devices.

![issue1](https://cloud.githubusercontent.com/assets/5687388/9442359/9078c30e-4a49-11e5-9561-d6b3851e2e4d.jpg)

**Comment by kamranShahidJarral** [comment]
done
